//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace StringWebService.WebStringWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StringWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class StringWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VowelsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExtractStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckSubStringOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StringWebService() {
            this.Url = global::StringWebService.Properties.Settings.Default.StringWebService_WebStringWebService_StringWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VowelsCountCompletedEventHandler VowelsCountCompleted;
        
        /// <remarks/>
        public event ExtractStringCompletedEventHandler ExtractStringCompleted;
        
        /// <remarks/>
        public event CheckSubStringCompletedEventHandler CheckSubStringCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VowelsCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int VowelsCount(string str) {
            object[] results = this.Invoke("VowelsCount", new object[] {
                        str});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void VowelsCountAsync(string str) {
            this.VowelsCountAsync(str, null);
        }
        
        /// <remarks/>
        public void VowelsCountAsync(string str, object userState) {
            if ((this.VowelsCountOperationCompleted == null)) {
                this.VowelsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVowelsCountOperationCompleted);
            }
            this.InvokeAsync("VowelsCount", new object[] {
                        str}, this.VowelsCountOperationCompleted, userState);
        }
        
        private void OnVowelsCountOperationCompleted(object arg) {
            if ((this.VowelsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VowelsCountCompleted(this, new VowelsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExtractString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExtractString(string str1, int start, int len) {
            object[] results = this.Invoke("ExtractString", new object[] {
                        str1,
                        start,
                        len});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExtractStringAsync(string str1, int start, int len) {
            this.ExtractStringAsync(str1, start, len, null);
        }
        
        /// <remarks/>
        public void ExtractStringAsync(string str1, int start, int len, object userState) {
            if ((this.ExtractStringOperationCompleted == null)) {
                this.ExtractStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtractStringOperationCompleted);
            }
            this.InvokeAsync("ExtractString", new object[] {
                        str1,
                        start,
                        len}, this.ExtractStringOperationCompleted, userState);
        }
        
        private void OnExtractStringOperationCompleted(object arg) {
            if ((this.ExtractStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExtractStringCompleted(this, new ExtractStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckSubString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckSubString(string str, string substr) {
            object[] results = this.Invoke("CheckSubString", new object[] {
                        str,
                        substr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckSubStringAsync(string str, string substr) {
            this.CheckSubStringAsync(str, substr, null);
        }
        
        /// <remarks/>
        public void CheckSubStringAsync(string str, string substr, object userState) {
            if ((this.CheckSubStringOperationCompleted == null)) {
                this.CheckSubStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckSubStringOperationCompleted);
            }
            this.InvokeAsync("CheckSubString", new object[] {
                        str,
                        substr}, this.CheckSubStringOperationCompleted, userState);
        }
        
        private void OnCheckSubStringOperationCompleted(object arg) {
            if ((this.CheckSubStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckSubStringCompleted(this, new CheckSubStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void VowelsCountCompletedEventHandler(object sender, VowelsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VowelsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VowelsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ExtractStringCompletedEventHandler(object sender, ExtractStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtractStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExtractStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CheckSubStringCompletedEventHandler(object sender, CheckSubStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckSubStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckSubStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591